### PR TITLE
Show -0.0 sign

### LINKED ISSUE #152: Should `show (-0.0)` produce "-0.0"?
Currently, `show (-0.0) == "0.0"`, which is arguably wrong, since even though `-0` and `0` do compare equal, they produce different results when dividing by either of them.

### PR DESCRIPTION
**Pull request by kl0tl**
Close https://github.com/purescript/purescript-prelude/issues/152.

### CODE REVIEW

**Comment by hdgarrood** [comment]
Ah, I’m more conflicted about this after looking at the diff and realising that JS’s .toString doesn’t include the minus sign for negative zero. I can definitely see this causing breakage at runtime without warning. I’ll see if I can find anything about this in IEEE 754.

**Comment by hdgarrood** [comment]
It turns out IEEE 754 doesn't say anything about functions like `.toString()` for formatting floating point numbers as strings for display.

**Comment by kl0tl** [comment]
If we don’t infringe IEEE 754 by showing positive and negative zeroes differently is there any reason not to do it?

**Comment by hdgarrood** [comment]
I think the reasons not to do it are that a) people may be relying on the current behaviour, and b) there might be a good reason why JS's `.toString()` doesn't distinguish positive and negative zero, and I'd like to look into that first. It's probably worth seeking out some examples of the stance other languages have taken on this question and what conclusions they came to. This is definitely not a decision we'll want to rush; much as I'd prefer this wasn't the case, in practice people will be using `Show Number` for a whole lot of different things beyond just debugging and the repl.

**Comment by hdgarrood** [comment]
https://github.com/rust-lang/rust/issues/20596 and https://github.com/rust-lang/rfcs/issues/1074 are relevant

**Comment by JordanMartinez** [comment]
[This comment in runt-lang/rfcs#1074](https://github.com/rust-lang/rfcs/issues/1074#issuecomment-718243936) shows how most popular languages handle this.

One could get around this problem by specifying a newtype that will always include the sign, but that seems like overkill.

**Comment by kl0tl** [comment]
I suspect that Number.prototype.toString hides the sign of negative zero to not leak its existence to end users? You’re right that people are probably using Show to display numbers in user interfaces (I certainly did it myself 😬). Perhaps we should rather make your Debug class the default in the REPL, show the sign of negative zero there and even deprecate Show if we’re feeling bold.

**Comment by hdgarrood** [comment]
I would love to deprecate Show in favour of Debug eventually, yes.

**Comment by kl0tl** [comment]
Let’s close this for now and reconsider when replacing Show with Debug then?

**Comment by hdgarrood** [comment]
Works for me.

**Pull request closed without merging**
