### PR TITLE
Fix warnings and doc-comments for 0.14

### PR DESCRIPTION
**Pull request by hdgarrood**
Like #226, except that it's based on the previous PRs #209 and #211 which mysteriously got closed - apparently by me but I don't remember doing that - and GitHub won't let me reopen them either. I'd like to merge this one instead of #226 since it preserves @Thimoteus's authorship as well as the doc-comment update in NaturalTransformation.

### CODE REVIEW

**Comment by JordanMartinez** [comment]
I think the branch got deleted and that's why the PRs were closed

**Comment by hdgarrood** [comment]
Both branches still exist on the respective repositories, that’s how I was able to put this PR together

**Review by JordanMartinez — APPROVED** [review]

**Comment by Thimoteus** [comment]
Oh cool, thanks for keeping my commits!

**Comment by hdgarrood** [comment]
Sure 🙂

**Pull request merged**
