### PR TITLE
Update `Field`

### LINKED ISSUE #128: Re-add DivisionRing?
I am working on a quaternion library and I was wondering if it might make sense to add a `DivisionRing` type class again, as follows:

```purescript
class Ring a <= DivisionRing a where
  recip :: a -> a
```

with the law that `x * recip x = recip x * x = one` for all nonzero `x`. There's no requirement for the ring to be commutative, and so this would allow us to provide a `DivisionRing Quaternion` instance.

If we were going to do this, we should change `Field` so that `DivisionRing` is a subclass as well.

Now of course with any `EuclideanRing` you can simply write `one / x` for `recip x`. Also, admittedly, the only 'useful' instance I can think of is `Quaternion`; I did some googling and wasn't really able to find any other useful examples of non-commutative division rings. But I think it would be nice to have a way of asking for the multiplicative inverse of an element of an arbitrary division ring without requiring it to be commutative.

### LINKED ISSUE #132: Clean up numeric hierarchy
After #128, we now have a couple of small problems:

* `Field` is exactly `CommutativeRing` and `DivisionRing`; forcing people to declare an extra `Field` instance doesn't really add anything.
* `Field` should have `DivisionRing` as a subclass, since every `Field` is a `DivisionRing`.

As far as I can tell, there are two options for addressing this:

**Option 1:** Change `Field` as follows:

```purescript
class (DivisionRing a, CommutativeRing a) <= Field a
instance field :: (DivisionRing a, CommutativeRing a) => Field a
```

So that no additional `Field` instances should be declared anywhere, and instead the single `Field` instance allows people to use a `Field` constraint wherever a type has both `DivisionRing` and `CommutativeRing` instances. If we did this, it would only be a breaking change for people who had declared `Field` instances for types in their own code; functions with `Field` constraints should continue to work as before.

**Option 2:** Wait for constraint kinds and define `Field` in terms of a class `class Both (a :: Constraint) (b :: Constraint)` (is that accurate?)

### PR DESCRIPTION
**Pull request by garyb**
Resolves #132

### CODE REVIEW

**Comment by hdgarrood** [comment]
Every field is a euclidean ring, so I think it might be best to keep the EuclideanRing constraint. In fact with what's in this PR, you wouldn't be able to write a function which uses `/` and which only has a `Field` constraint, right?

How about this instead:

```purescript
class (EuclideanRing a, DivisionRing a) <= Field a
instance (EuclideanRing a, DivisionRing a) => Field a
```

**Comment by hdgarrood** [comment]
Also this relates to #132, not #128, right?

**Comment by garyb** [comment]
I did wonder about that, in the other PR I had it with the `EuclideanRing` constraint but then looking at it again today I thought that might have been a mistake :smile:

**Comment by hdgarrood** [comment]
Also I think it might be worth mentioning that every type with law-abiding `DivisionRing` and `CommutativeRing` instances only really has one sensible law-abiding `EuclideanRing` implementation, where `div a b = a * recip b`, `mod _ _ = zero`, and `degree _ = 1`; see <https://a-guide-to-the-purescript-numeric-hierarchy.readthedocs.io/en/latest/euclidean-rings.html>, where it says "start from "Let F be a field, and suppose f:F∖{0}→N is a euclidean function". `degree` must be constant; any return value will work, so you might as well choose 1.

**Comment by hdgarrood** [comment]
Sorry, I didn't notice you had updated this, but there's a couple of things I think are not quite right here (in the docs). Do you mind if I send another PR?

**Comment by hdgarrood** [comment]
Oh actually, `EuclideanRing` implies `CommutativeRing`, so adding the `CommutativeRing` superclass won't do anything. With this commit, we have a `Field Int` instance, which is definitely wrong. It should have `EuclideanRing` and `DivisionRing` superclasses. I'll send a PR in a moment.

**Comment by garyb** [comment]
Oops, glad someone is paying attention :wink:

**Pull request merged**
