### PR TITLE
fixes #51: properly escape output of Show instance for Char

### LINKED ISSUE #51: Show instance for Char should escape backslash character
In addition to the tick `'`, the backslash should be escaped in `showChar`. Currently:

``` purs
> print '\\'
'\'
```

### PR DESCRIPTION
**Pull request by michaelficarra**
Fixes #51.

### CODE REVIEW

**Comment by michaelficarra** [comment]
Ping @paf31 @garyb. I've rebased these PRs after the jshint config fix and now they pass CI.

**Comment by paf31** [comment]
:+1: Thanks!

**Comment by michaelficarra** [comment]
@garyb Can we get these PRs merged?

**Comment by garyb** [comment]
Sorry for the delay, thanks for these!

**Pull request merged**
