### PR TITLE
Add Boolean Semiring instance

### PR DESCRIPTION
**Pull request by hdgarrood**
Credit for noticing this goes to @michaelficarra.

### CODE REVIEW

**Comment by garyb** [comment]
Could make it an instance for values with a `BoundedLattice` instance generally perhaps? Not sure if that might be dodgy in regard to overlaps though.

**Comment by hdgarrood** [comment]
Maybe a newtype in the spirit of `Multiplicative` or `Additive` would make sense?

``` purescript
newtype SupInf a = SupInf a
instance semiringSupInf :: BoundedLattice a => Semiring (SupInf a)
```

edit: with a better name, perhaps

**Comment by michaelficarra** [comment]
:grin: I helped!

**Comment by garyb** [comment]
@hdgarrood that would make sense, perhaps belongs in `purescript-semirings` then. Indeed I don't know what the name would be though :wink:

**Comment by hdgarrood** [comment]
`LatticeSemiring` perhaps? Also I guess there wouldn't be a need for a `Boolean Semiring` instance if we had that?

**Comment by garyb** [comment]
Yeah, that's what I'd suggest - we just have the newtype'd version.

**Comment by hdgarrood** [comment]
:+1:

**Comment by paf31** [comment]
Doesn't every lattice have two semirings?

**Comment by hdgarrood** [comment]
I'm not sure. Is the other one you're thinking of obtained by flipping the order (like Haskell's `Down`) and swapping `(+)` with `(*)`?

**Comment by paf31** [comment]
Yes, I think so.

**Comment by hdgarrood** [comment]
Maybe we could do that as `instance Semiring a => Semiring (Down a) where [...]`?

**Comment by garyb** [comment]
:+1:

**Pull request closed without merging**
