### PR TITLE
Change NoConstructors to a newtype over Void

### LINKED ISSUE #247: [generics-rep] newtype NoConstructors = NoConstructors Void
This way you can use `absurd`. Although if we implement https://github.com/purescript/purescript/issues/2922 then this is not necessary.

### PR DESCRIPTION
**Pull request by JordanMartinez**
Fixes #247﻿

### CODE REVIEW

**Comment by kl0tl** [comment]
I don’t think we should do this: I doubt being able to eliminate terms of type `NoConstructors` with `absurd` is useful enough when we can already use `unsafeCrashWith "unreachable"` or `unsafeCoerce`.

**Comment by hdgarrood** [comment]
I do think that setting things up so that you don’t need to use unsafe functions is generally worth it, but since this doesn’t appear to be a breaking change we can deal with it after 0.14.0.

**Comment by kl0tl** [comment]
I agree, but here I'd prefer to not commit to this encoding yet so we can try to make some progress on https://github.com/purescript/purescript/issues/2922.

**Comment by JordanMartinez** [comment]
Ok. I'll close this then. Thanks for the feedback.

**Pull request closed without merging**
