### PR TITLE
Fix show number again

### PR DESCRIPTION
**Pull request by hdgarrood**
cc @AppShipIt @michaelficarra, refs #72

### CODE REVIEW

**Comment by michaelficarra** [comment]
@hdgarrood See my comment in #72. I'd prefer that implementation.

**Comment by hdgarrood** [comment]
Unfortunately, your implementation doesn't work for numbers with exponents:

```
Error: For 1e+21, expected 1e+21, got: 1e+21.0.
```

**Comment by texastoland** [comment]
Agreed it's nice (less coercion) but that's the case I found too.

**Comment by michaelficarra** [comment]
Ah, got it. :+1: then.

**Comment by garyb** [comment]
Thanks everyone involved in this!

**Pull request merged**
