### PR TITLE
add ap = apply law

### PR DESCRIPTION
**Pull request by Thimoteus**

### CODE REVIEW

**Comment by paf31** [comment]
👍 Makes sense to me

**Comment by garyb** [comment]
I know it's exactly the same thing, but wouldn't people usually say `apply = ap` (since you define `apply` for the instance but `ap` is derived)? Either way 💯

**Comment by Thimoteus** [comment]
Ah. I was thinking putting `ap` on the LHS since it's defined in the same module. Something about reading left-to-right, seeing `ap`, asking "wait, what's that? oh, it's a few lines below," then reading `= apply`.

**Comment by garyb** [comment]
Thanks! Forgot about this one until a relevant discussion popped up today :wink:

**Pull request merged**
