### PR TITLE
Adds yoneda-inspired thunks for Category and Monoid

### PR DESCRIPTION
**Pull request by mikesol**
**Description of the change**

I've written these functions 3-4 times in various repos here and there, and I think they're of enough utility to be in the prelude.

Both of them are yoneda-inspired and basically fish out a value from a closure. For example, `cayo` can be used with profunctor lenses, ie `t = cayo (_2 <<< _2 <<< _2) (1 /\ 2 /\ 3 /\ 4)`.

If folks are ok with this, lemme know and I'll make the relevant changelog entries.

**Checklist:**

- [ ] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [ ] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Just curious, but is there any precedence for these functions? And could you provide an example of how you've used them?

**Comment by mikesol** [comment]
> Just curious, but is there any precedence for these functions? And could you provide an example of how you've used them?

I can't find any precedence, but I've used the logic from `cayo` when working with lenses and wanting to make sure a law holds. I also used `moyo` when coming up with a set of laws for `IsEvent` from event.

Both functions turn the use of identity and mempty into a verb (a function) instead of a noun (the term), so they felt more laws-y to read.

The functions are trivial to write, so it's easy to implement them _ad hoc_. The way I'm framing a discussion is, given how trivial and self-evident they are, is there something "natural" about them that would only make sense in a prelude? Or is there another lib that'd be a better fit? Or are they too trivial/limited to go in any library & they should be hand-rolled when needed?

**Comment by JordanMartinez** [comment]
I think I'm against adding them here for the following reasons:
- no precedence
- it's not clear to me that multiple people benefit from these being defined here
- it's not clear to me whether there may be other alternatives to using `cayo`/`mayo` that could also address the need you have for using them.

**Comment by mikesol** [comment]
👍 I'll close the PR.

**Pull request closed without merging**
