### PR TITLE
#1251: move Int bounds to FFI

### PR DESCRIPTION
**Pull request by andyarvanitis**
For enhancement reported in issue #1251

### CODE REVIEW

**Comment by paf31** [comment]
Looks fine to me. @michaelficarra @garyb Look ok?

**Comment by garyb** [comment]
Looks good to me, this is in #41 as well, but that's not going in for a while most likely, so :+1:

**Comment by michaelficarra** [comment]
LGTM too. :+1:

**Comment by andyarvanitis** [comment]
Thanks, guys!

**Comment by paf31** [comment]
Not a breaking change, so minor version bump, ok?

**Comment by michaelficarra** [comment]
Patch.

**Comment by paf31** [comment]
I don't think I've ever made a patch release. Would that be 0.1.2.1, then?

**Comment by michaelficarra** [comment]
No no no, [semver](http://semver.org/) versions are MAJOR DOT MINOR DOT PATCH.

**Comment by paf31** [comment]
Ok, so I just meant to say patch. < version 1.0 gets slightly confusing.

**Comment by paf31** [comment]
Done, thanks!

**Pull request merged**
