### PR TITLE
Added compose math symbol

### PR DESCRIPTION
**Pull request by Risto-Stevcev**

### CODE REVIEW

**Comment by paf31** [comment]
We have stuck to non-Unicode in the core libraries so far. That might just be because we always have, but we should make a decision about it, since this would be the first use of it.

**Comment by michaelficarra** [comment]
I don't see any reason to avoid non-ASCII aliases. It's not like you're forcing user code to be written that way.

**Comment by paf31** [comment]
I can think of the following reasons:

- It's harder to read in my opinion.
- It's harder to input.
- It's intimidating for beginners. I remember being put off by Agda's syntax, for example.
- It's another way to do something we can already do, and we should have one preferred way.

We're not forcing code to be written this way, but it will encourage it.

**Comment by Risto-Stevcev** [comment]
Why is this any different than having these though? `∷ ← → ⇐ ⇒ ∀`
All of those concerns apply to those also

**Comment by Thimoteus** [comment]
Are there core libs that use unicode symbols like ∀ and →?

**Comment by paf31** [comment]
No, we don't use them in the core libraries.

**Comment by hdgarrood** [comment]
It looks like we've come to a decision then, so I'll close this.

**Pull request closed without merging**
