### PR TITLE
Fix warnings revealed by v0.14.1 PS release

### PR DESCRIPTION
**Pull request by JordanMartinez**
**Description of the change**

The `v0.14.1` PS release now reports warnings on more things. CI will fail due to these new warnings. This PR fixes those warnings.

Backlinking to purescript/purescript#4071

---

**Checklist:**

- [x] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [ ] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Review by hdgarrood — APPROVED** [review]
Thanks!

**Comment by JordanMartinez** [comment]
Do we need another approval on this before it can be merged?

**Comment by hdgarrood** [comment]
We don't need another approval, because you're on the core team so you count too.

**Comment by JordanMartinez** [comment]
Great! That'll make this easier to do.

**Comment by hdgarrood** [comment]
@thomashoneyman it looks to me like CI is using 0.14.0 here - do you know if/when it'll switch to 0.14.1? Is some kind of manual intervention required in setup-purescript?

**Comment by thomashoneyman** [comment]
setup-purescript updates nightly, so by tomorrow it’ll be updated. However we can always manually update the versions file in that repo and it’ll take effect immediately.

**Comment by hdgarrood** [comment]
Ah I see - good to know, thanks.

**Pull request merged**
