### PR TITLE
Fix intDegree on edge cases

### LINKED ISSUE #113: degree bottom > top
`degree` on integers returns an out-of-bounds integer.

### PR DESCRIPTION
**Pull request by no-longer-on-githu-b**
Fixes #113.

### CODE REVIEW

**Review by hdgarrood — APPROVED** [review]

**Comment by garyb** [comment]
I wonder if this should be clamped rather than modulo, due to the intended behaviour of `degree`. @hdgarrood?

**Comment by hdgarrood** [comment]
Ah good point. Do we have `degree (bottom :: Int) == bottom` with this PR?

**Comment by no-longer-on-githu-b** [comment]
I have no clue, but with this PR yes, `degree bottom == bottom`.

Sent from my iPhone.

**Comment by hdgarrood** [comment]
I think @garyb is right, `degree bottom == top` would be better I think.

**Comment by no-longer-on-githu-b** [comment]
Alright, changed that.

**Review by hdgarrood — APPROVED** [review]

**Pull request merged**
