### PR TITLE
Explain the magic numbers for Bounded Int.

### PR DESCRIPTION
**Pull request by chexxor**
This question came up in the chat room.

### CODE REVIEW

**Comment by hdgarrood** [comment]
I think it would make more sense to put this on the `Bounded Int` instance in the `purs` file, so that it shows up in the HTML docs. Also, I don't think we should refer to floating point at all, since `Int` really has very little to do with floating point; the fact that `Int` is sort of like `double` underneath is only an implementation detail for the JS backend.

Here's what I'd suggest instead:

> The `Bounded Int` instance has `top :: Int` equal to `2^31 - 1`, and `bottom :: Int` equal to `-2^31`, since these are the largest and smallest integers representable by twos-complement 32-bit integers respectively.

**Comment by chexxor** [comment]
Great ideas, @hdgarrood - I've moved the docs and taken your suggestion. Your explanation is more succinct and the reason is more satisfying to the curious mind coming to find the answer.

Hope it's possible to squash these into one commit - would be weird to add 3 commits to implement this patch, haha.

**Comment by hdgarrood** [comment]
Thanks! And also good idea to clarify this in the docs in the first place. I'd just like to remove the indentation on the second and third lines of your doc-comment, just in case it messes up the formatting in the HTML docs.

We can squash and merge in one go with the merge button now, incidentally, which is nice.

**Comment by hdgarrood** [comment]
Oh also, I think it might also be good to preserve the backticks.

**Comment by garyb** [comment]
Thanks!

**Pull request merged**
