### PR TITLE
Relax constraint on (>>=)

### PR DESCRIPTION
**Pull request by hdgarrood**

### CODE REVIEW

**Comment by garyb** [comment]
:+1:

**Comment by paf31** [comment]
Oh wait, no, this breaks the optimizer. Reverting ...

**Comment by garyb** [comment]
We can fix that though?

**Comment by paf31** [comment]
Yes, but let's verify first?

**Comment by paf31** [comment]
I don't seem to be able to reopen this, sorry :(

**Comment by hdgarrood** [comment]
Shall I resubmit the same code?

**Comment by paf31** [comment]
Yes, please, but I'll merge once we have the compiler change ready to go.

**Pull request merged**
